### PR TITLE
Use fedora template and run phpab command with quiet option

### PR DESCRIPTION
**Pull request by r7l**
As said in #6 it might be better to use `fedora` in order to avoid the issue if 3rd parties decide to change include_path configuration within their code.

This PR changes the template from `fedora2` to `fedora` in all files. It also adds `--quiet` option in order to avoid cluttering the build output of Portage for no real reason.

I've also included some further cleanup and even found another missing dependency.

### CODE REVIEW

**Comment by fcool** [comment]
Sorry, but I cannot bring myself to accept this one.

1. The fedora2 template is used by the original gentoo ebuilds
2. If the omitted absolute path gets broken by single third-party packages, this can be fixed there, maybe by patching the removal of include_path or using absolute paths there.
3. being able to rely on the include path allows the package management to rearrange packages (as long as the relative path stays intact). Dropping this flexibility everywhere because single packages struggle does more harm than benefit.

**Comment by r7l** [comment]
I can't really follow your statement. 

Where do you see `fedora2` being used in Gentoo? If i take a look [into dev-php in the main Portage tree](https://github.com/gentoo/gentoo/tree/master/dev-php), i see static autoload.php files in [pretty](https://github.com/gentoo/gentoo/blob/master/dev-php/psr-log/files/autoload.php) [much](https://github.com/gentoo/gentoo/blob/master/dev-php/xdebug-handler/files/autoload.php) [every](https://github.com/gentoo/gentoo/blob/master/dev-php/webmozart-assert/files/autoload.php) [package](https://github.com/gentoo/gentoo/blob/master/dev-php/json-schema/files/autoload.php). Non of them seem to use either `fedora` or `fedora2` template as they all have code not being in any of them:

```
if (!class_exists('Fedora\\Autoloader\\Autoload', false)) {
    require_once '/usr/share/php/Fedora/Autoloader/autoload.php';
}
```

And this code is as static as `fedora` template. So it seems as the situation you're mention in **3** has been the default in Gentoo for years.

Don't get me wrong but this `include_path` option seems to be an ancient relic in PHP world. Using another package manager beside Composer to install PHP packages is considered an antipattern in PHP world anyways. I don't see it supported anywhere. Every install instruction is based of `composer require $package` or maybe download a prebuild *phar* file. You're always on your own with this. People will simply refuse to help you once you've said you install with another package manager. I've had this situation more then once.

But yes it would be possible to remove or alter the `include_path` and i can do that.

**Comment by fcool** [comment]
See all newer PHP ebuilds:
- sebastian-object-reflector
- myclabs-deepcopy
- phpunit
- PHP_CodeCoverage
- phar-io-version
- reactphp-promise
- theseer-Autoload
- phar-io-manifest
- jsonlint
- sebastian-type
- metadata-minifier
- semver
- sebastian-code-unit-reverse-lookup
- doctrine-instantiator
- theseer-tokenizer

**Comment by r7l** [comment]
I see. Nevermind the PR then and sorry to bother. Even if this is a large number of packages, seems like i've missed them and just looked through the ones still using static autoload files. This seems to be pretty random and not even mentioned in the wiki. Actually they even tell people to use static autoload files there.

**Comment by fcool** [comment]
Never mind! Your contributions are highly appreciated!

**Pull request closed without merging**
